# This file was generated by GoReleaser. DO NOT EDIT.
cask "oidc" do
  name "oidc"
  desc "Command line tool to interact with Open ID Connect providers."
  homepage "https://github.com/chatdoux/oidc-cli"
  version "1.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oidc"
  bash_completion "completions/oidc.bash"
  zsh_completion "completions/oidc.zsh"
  fish_completion "completions/oidc.fish"

  on_macos do
    on_intel do
      url "https://github.com/chatdoux/oidc-cli/releases/download/v#{version}/oidc-cli_Darwin_x86_64.tar.gz"
      sha256 "00a0fb0718b0cfcfc720ee95b20acf256b724ed7680f184ea01e1d931e913245"
    end
    on_arm do
      url "https://github.com/chatdoux/oidc-cli/releases/download/v#{version}/oidc-cli_Darwin_arm64.tar.gz"
      sha256 "170e8b0aa816e940c0a8788a80967681984abcb5fc2342b8173b26dcc2b49d6d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/chatdoux/oidc-cli/releases/download/v#{version}/oidc-cli_Linux_x86_64.tar.gz"
      sha256 "9e9c8428ef6c8d143ccec23d42822d8422362f4c6f35997c1787f03296cd1fbb"
    end
    on_arm do
      url "https://github.com/chatdoux/oidc-cli/releases/download/v#{version}/oidc-cli_Linux_arm64.tar.gz"
      sha256 "aeaf4bf8bdd466eeeebedfdea3d75a73b4c6966387be3b633295329fde829732"
    end
  end

  caveats do
    "How to use this binary"
  end

  # No zap stanza required
end
