# This file was generated by GoReleaser. DO NOT EDIT.
cask "oidc" do
  name "oidc"
  desc "Command line tool to interact with Open ID Connect providers."
  homepage "https://github.com/chatdoux/oidc-cli"
  version "1.0.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oidc"
  bash_completion "completions/oidc.bash"
  zsh_completion "completions/oidc.zsh"
  fish_completion "completions/oidc.fish"

  on_macos do
    on_intel do
      url "https://github.com/chatdoux/oidc-cli/releases/download/v#{version}/oidc-cli_Darwin_x86_64.tar.gz"
      sha256 "b4e55497c2ff07a560ff749397942ee5e0047c885546b54483102003b5c77de7"
    end
    on_arm do
      url "https://github.com/chatdoux/oidc-cli/releases/download/v#{version}/oidc-cli_Darwin_arm64.tar.gz"
      sha256 "ff7b9b5ee85eef46492fa531ab4d99497f1017318ab014c38d9d6d91d7c777fd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/chatdoux/oidc-cli/releases/download/v#{version}/oidc-cli_Linux_x86_64.tar.gz"
      sha256 "4a3fd7658a4974ac99c0e5f43a13d486b35c646cfff2d743c2b9cf7036626145"
    end
    on_arm do
      url "https://github.com/chatdoux/oidc-cli/releases/download/v#{version}/oidc-cli_Linux_arm64.tar.gz"
      sha256 "f73927a68593e4300fafca4941e59e8629cf834cd65dd0aabc8a59db50f6140f"
    end
  end

  caveats do
    "How to use this binary"
  end

  # No zap stanza required
end
